# Generated by Django 4.2.2 on 2023-06-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turmas',
            new_name='Turma',
        ),
    ]
