# Generated by Django 4.2.6 on 2023-10-12 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_aluno"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aluno",
        ),
    ]
