# Generated by Django 4.2.6 on 2023-10-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_delete_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.club",
            ),
        ),
    ]
