# Generated by Django 4.2.6 on 2023-10-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_client_club"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_time", models.DateTimeField(max_length=60)),
                ("out_time", models.DateTimeField(max_length=60)),
                (
                    "room_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.room_class",
                    ),
                ),
            ],
        ),
    ]
