# Generated by Django 4.2.2 on 2023-07-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aluno_email_alter_aluno_telefone_and_more'),
        ('core', '0006_club'),
    ]

    operations = [
    ]
