# Generated by Django 4.2.2 on 2023-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20230715_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=24)),
                ('data_nascimento', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=14, null=True)),
                ('senha', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
